#!/usr/bin/env bash
#
# enable_secrets
#
# Sequentially create N kv secrets engine mounts in Vault
#
# shellcheck disable=SC2086,SC2089,SC2090,SC1090,SC1091
#

HERE="$(pwd)"
SKYDOME="$(while [ "$HERE" != "/" ] ; do HERE=$(dirname "$HERE"); find "$HERE" -maxdepth 1 -name skydome; done)"
if [ -z "$SKYDOME" ]; then
  SKYDOME=./skydome
fi
. $SKYDOME

program="$(basename "$0")"

if [ $# -eq 0 ]
  then
    msg alert "Usage: ${program} <number_of_secrets_mounts>"
    exit 1
fi

check_vault() {
  if command nc; then
    PORT_CHECK="nc -z locahost 8200";
  elif command timeout; then
    PORT_CHECK="timeout 1 bash -c '</dev/tcp/localhost/8200'"
  elif command gtimeout; then
    PORT_CHECK="gtimeout 1 bash -c '</dev/tcp/localhost/8200'"
  fi
}

gen_secrets() {
  while [[ $i -le $1 ]]; do
    mount_path="$(openssl rand -hex 8)"
    vault secrets enable -path=$mount_path kv
    #msg secret "KV Secrets Engine mounted at path: ${mount_path}"
    ((i = i + 1))
  done
}

if $PORT_CHECK; then
  gen_secrets "$@"
  msg complete "Generated $1 KV Secrets Engine mounts!"
else
  echo "Not sure if Vault is reachable at localhost! Giving up!"
  exit 1
fi
